apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dependency-installer
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: dependency-installer
  template:
    metadata:
      labels:
        name: dependency-installer
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: installer
        image: ubuntu:20.04
        command: ["/bin/bash", "-c"]
        args:
        - |
          if [ ! -f /tmp/dependencies_installed ]; then
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y curl wget git vim unzip htop
            # Install Azure CLI
            curl -sL https://aka.ms/InstallAzureCLIDeb | bash
            az aks install-cli
            # Download jQuery
            wget https://code.jquery.com/jquery-3.6.0.min.js -O /usr/local/bin/jquery.js
            # Add more installation commands here
            touch /tmp/dependencies_installed
          fi
          
          # Keep the container running
          sleep infinity
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-root
          mountPath: /host
      volumes:
      - name: host-root
        hostPath:
          path: /
      terminationGracePeriodSeconds: 30