apiVersion: v1
kind: ServiceAccount
metadata:
  name: shipper-sa
  namespace: shipper-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shipper-role
  namespace: shipper-backend
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete", "get", "list", "update"]
- apiGroups: ["shipwright.io"]
  resources: ["builds", "buildruns"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shipper-rolebinding
  namespace: shipper-backend
subjects:
- kind: ServiceAccount
  name: shipper-sa
roleRef:
  kind: Role
  name: shipper-role
  apiGroup: rbac.authorization.k8s.io